Repository School-of-Company/Bitgouel-Server, pull requests merged in 2023-10, with the labels that each got.

#2 프로젝트 멀티모듈 세팅
  .editorconfig
  .gitattributes
  .github/CODEOWNERS
  .gitignore
  Dockerfile
  README.md
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/bitgouel/team/msg/BitgouelApplication.kt
  bitgouel-api/src/main/resources/application.yml
  bitgouel-api/src/test/kotlin/bitgouel/team/msg/BitgouelApplicationTests.kt
  bitgouel-batch/build.gradle.kts
  bitgouel-domain/build.gradle.kts
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, 1️⃣ Priority: High, 2️⃣ Priority: Medium, 3️⃣ Priority: Low, ♻️ Refactor, ⚙ Setting, ⚡️ Simple, ⚡️performance, ✅ Test, ✨ Feature, 🌏 Deploy, 🐞 Bug, 📝 Docs, 🙋‍♂️ Question, 🪡 Want

#6 5 feature/user domain
  .github/CODEOWNERS
  README.md
  assets/img/bitgoeul_erd.png
  assets/img/project_diagram.png
  bitgouel-api/src/main/kotlin/bitgouel/team/msg/BitgouelApplication.kt
  bitgouel-domain/build.gradle.kts
  bitgouel-domain/src/main/kotlin/base/BaseTimeEntity.kt
  bitgouel-domain/src/main/kotlin/base/BaseUUIDEntity.kt
  bitgouel-domain/src/main/kotlin/domain/user/enums/Authority.kt
  bitgouel-domain/src/main/kotlin/domain/user/enums/SignUpStatus.kt
  bitgouel-domain/src/main/kotlin/domain/user/model/User.kt
  bitgouel-domain/src/main/kotlin/domain/user/repository/UserRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature, 📝 Docs

#12 Batch Application, SQL 세팅
  bitgouel-batch/build.gradle.kts
  bitgouel-batch/src/main/kotlin/team/msg/BatchApplication.kt
  bitgouel-batch/src/main/kotlin/team/msg/common/BaseJobParameter.kt
  bitgouel-batch/src/main/resources/application.yml
  bitgouel-batch/src/main/resources/schema.sql
  bitgouel-domain/src/main/kotlin/common/LoggerDelegator.kt
Labels: 1️⃣ Priority: High, ⚙ Setting

#19 18 entity and enum typing error
  bitgouel-domain/src/main/kotlin/team/msg/domain/school/enums/HighSchool.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
Labels: ⚡️ Simple, 🐞 Bug

#25 강의 관련 엔티티 세팅
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/enum/ApproveStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enum/LectureType.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/enums/SignUpStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#44 #44 HttpLoggingAspect 클래스 작성
  bitgouel-api/src/main/kotlin/team/msg/common/aop/HttpLoggingAspect.kt
  bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#39 34 학생 활동 정보 추가
  bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/StudentNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/CreateStudentActivityRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/CreateStudentActivityWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/teacher/exception/TeacherNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/teacher/exception/constant/TeacherErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/repository/TeacherRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#49 #27 강의 개설 신청
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/AuthController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/InvalidLectureTypeException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#50 48 feat/student activity update
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/StudentActivityNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentActivityErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/UpdateStudentActivityRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/UpdateStudentActivityWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseTimeEntity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#58 BaseUUIDEntity() Persistable 구현과 JpaRepository 기능 관련 이슈 해결 트러블슈팅
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/ulid/ULIDGenerator.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/admin/model/Admin.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/bbozzak/model/Bbozzak.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/model/CompanyInstructor.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
Labels: 1️⃣ Priority: High, ⚡️performance

#63 #62 getIdentifier 충돌 이슈 해결
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/admin/model/Admin.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/bbozzak/model/Bbozzak.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/model/CompanyInstructor.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/model/Government.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/professor/model/Professor.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#59 54 feat/delete student activity
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#65 61 feat/student activity reject and delete
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/ForbiddenStudentActivityException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentActivityErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#69 68 feat/approve student activity
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#80 79 feat/docker compose redis
  Dockerfile
  bitgouel-api/src/main/kotlin/team/msg/global/config/RedisConfig.kt
  docker-compose.yml
Labels: 1️⃣ Priority: High, 🌏 Deploy

#83 82 Bitgouel Application HealthCheckController
  bitgouel-api/src/main/kotlin/team/msg/domain/health/HealthCheckController.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#77 71 feat/student activity list
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/CreateStudentActivityWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#85 create :: bitgouel cd scripts
  .github/workflows/bitgouel-cd.yml
  scripts/deploy.sh
Labels: 1️⃣ Priority: High, ✨ Feature

#87 chore :: underbar to space
  .github/workflows/bitgouel-cd.yml
Labels: 1️⃣ Priority: High, 🌏 Deploy

#89 88 codedeploy 적용
  .github/workflows/bitgouel-cd.yml
  appspec.yml
Labels: 1️⃣ Priority: High, 🌏 Deploy

#92 health check controller response entity 적용
  bitgouel-api/src/main/kotlin/team/msg/domain/health/HealthCheckController.kt
Labels: 1️⃣ Priority: High
