Repository School-of-Company/Bitgouel-Server, pull requests merged in 2023-12, with the labels that each got.

#189 # 188 전화번호 정규식 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/BbozzakSignUpWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/CompanyInstructorSignUpWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/GovernmentSignUpWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/ProfessorSignUpWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/StudentSignUpWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/presentation/data/web/TeacherSignUpWebRequest.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#191 update :: feed type enum INFORM -> NOTICE
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/enums/FeedType.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#197 196 link -> links 로 이름 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/CreatePostRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/UpdatePostRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/response/PostResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/UpdatePostWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🐞 Bug

#193 192 게시글 삭제 기능
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/PostController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#199 게시글 삭제 권한 검증 로직 리팩토링
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#201 200 회원가입 거절 API
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#206 Post의 user_id 컬럼에 columnDefinition 옵션을 추가했습니다.
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug
