Repository School-of-Company/Bitgouel-Server, pull requests merged in 2023-11, with the labels that each got.

#95 81 feat/student activity query on club
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/bbozzak/repository/BbozzakRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/repository/CompanyInstructorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/repository/GovernmentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/professor/repository/ProfessorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/repository/TeacherRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#96 90 feature/query lecture
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/QueryAllLecturesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#107 105 feat/batchsize
  bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/repository/CompanyInstructorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/repository/GovernmentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/professor/repository/ProfessorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/repository/TeacherRepository.kt
Labels: 1️⃣ Priority: High, ⚡️performance

#108 #104 동아리 상세 조회 API 개발
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/teacher/model/Teacher.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#98 97 feature/query user my page
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#103 d99 feat/my studnet activity list
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#111 110 feature/setting post domain
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/enums/FeedType.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/repository/PostRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#113 112 feature/create user util
  bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#106 101 feature/setting querydsl
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/web/QueryAllLecturesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/QueryDslConfig.kt
  bitgouel-domain/build.gradle.kts
  bitgouel-domain/src/main/kotlin/team/msg/common/enums/ApproveStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureType.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/LectureRepositoryCustom.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/LectureRepositoryCustomImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/model/User.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️performance

#118 강의 리스트 전체 조회 response 요소 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#120 #119 DataInitializer 데이터 존재 여부 count 쿼리 성능 개선
  bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/CustomClubRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/CustomClubRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/CustomSchoolRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/CustomSchoolRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/SchoolRepository.kt
  scripts/deploy.sh
Labels: 1️⃣ Priority: High, ⚡️performance

#121 119 feat/data init count
  bitgouel-api/src/main/kotlin/team/msg/common/init/DataInitializer.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#122 114 학생 활동 상세 조회 api 개발
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#134 133 활동 날짜의 데이터 타입을 Date로 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/CreateStudentActivityRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/request/UpdateStudentActivityRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/CreateStudentActivityWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/web/UpdateStudentActivityWebRequest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#132 강의 리스트 조회에 response body에 강의 승인 정보 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#135 # 126 자격증 리스트 조회 학생 API 개발
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/response/CertificationResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/FaqController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/presentation/data/response/FaqResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FAQServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/service/FaqService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/certifiacation/repository/CertificationRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#141 강의 상태 버그 수정
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#139 # 136 자격증 리스트 조회 선생님 api 개발
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/ForbiddenCertificationException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/constant/CertificationErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#146 강의 리스트 조회 response body 변수 명 통일
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#144 # 142 자격증 수정 API 개발
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/exception/CertificationNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/mapper/CertificationRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/mapper/CertificationRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/CertificationController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/request/UpdateCertificationRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/presentation/data/web/UpdateCertificationWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/main/resources/application.yml
Labels: 2️⃣ Priority: Medium, ✨ Feature

#148 update :: response에 approve status 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#123 116 feature/create post
  bitgouel-api/src/main/kotlin/team/msg/domain/post/exception/ForbiddenPostException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/exception/constant/PostErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/PostController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/request/CreatePostRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/post/model/Post.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#153 deploy sh 배포 플로우 수정
  scripts/deploy.sh
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#161 add :: 학생 활동 리스트 조회 Response에 활동날짜 필드 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#165 165 소속 문자열 슬래시 구분
  bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#149 137 유저 전체 조회 및 검색 api
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/request/QueryUsersRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/web/QueryUsersWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/CustomUserRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/CustomUserRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#168 #167 Student 졸업생 전환 Batch Job Configuration 구성과 Batch 환경 구성
  bitgouel-batch/src/main/kotlin/team/msg/common/listener/BatchStepExecutionListener.kt
  bitgouel-batch/src/main/kotlin/team/msg/common/parameter/BaseJobParameter.kt
  bitgouel-batch/src/main/kotlin/team/msg/common/util/ParamUtil.kt
  bitgouel-batch/src/main/kotlin/team/msg/config/BatchBuilderFactoryConfiguration.kt
  bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateJobParameter.kt
  bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt
  bitgouel-batch/src/main/kotlin/team/msg/jobs/withdraw/.gitkeep
Labels: 1️⃣ Priority: High, ✨ Feature

#175 172 유저 회원가입 수락 API
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/UserAlreadyApprovedException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/constant/UserErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#181 180 feat/query student activity bug
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#184 183 학생 활동 상세 정보 Response에 approveStatus추가
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple
