Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-01, with the labels that each got.

#213 212 feat/inquery api
  bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLecturesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/InquiryAnswer.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryAnswerRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryRepository.kt
Labels: 2️⃣ Priority: Medium, 3️⃣ Priority: Low, ✨ Feature

#215 214 feat/query inquiry admin user
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/enums/AnswerStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/InquiryAnswer.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryCustom.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#210 동아리에 소속된 학생의 상세정보 조회 api
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#203 🔀 :: 202 유저 상세정보 조회 API
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#182 178 학생 활동 승인 시 학생활동 히스토리 업데이트
  bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/event/ApproveStudentActivityEvent.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/CustomStudentActivityHistoryRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/impl/CustomStudentActivityHistoryRepositoryImpl.kt
Labels: 1️⃣ Priority: High

#222 221 feat/inquiry detail delete
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/ForbiddenCommandInquiryException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/InquiryAnswerNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/InquiryNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/constant/InquiryErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryAnswerRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#224 223 feat/inquiry update
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/CreateInquiryAnswerRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/UpdateInquiryRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/CreateInquiryAnswerWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/UpdateInquiryWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/WithdrawStudentController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/service/WithdrawService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/service/WithdrawServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/model/Inquiry.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/withdrow/model/WithdrawStudent.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/withdrow/repository/WithdrawStudentRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#229 # 228 동아리 상세 조회 선생님 추가 반환
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/teacher/presentation/data/response/TeacherResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High

#227 강의 신청 취소 api
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/UnSignedUpLectureException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-batch/src/main/kotlin/team/msg/jobs/student/GraduateStudentJobConfiguration.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#231 문의사항 리스트의 컨텐츠 생성 일자 타입을 변경했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/response/InquiryResponse.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#233 비밀번호 변경 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/user/mapper/UserRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/mapper/UserRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/request/ModifyPasswordRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/web/ModifyPasswordWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#235 234 feature/fix admin query inquiry
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/mapper/InquiryMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/InquiryController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/request/QueryAllInquiresWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/presentation/web/QueryAllInquiresRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/custom/InquiryRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#244 🔀 :: 뽀짝쌤도 동아리에 속한 학생의 학생활동 조회 허용
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, 📝 Docs

#246 🔀 :: 학생 활동 상세 조회 API 권한 검증 로직 리팩토링
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor
