Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-07, with the labels that each got.

#478 강의 논리적 삭제 API 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/ForbiddenLectureException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/InstructorNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#481 삭제된 강의 데이터가 강의 리스트에서 조회되던 문제 해결
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#483 유관기관 cr(u)d를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/mapper/AuthRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/mapper/CertificationRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/mapper/EmailRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/faq/mapper/FaqRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/exception/AlreadyExistGovernmentException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/exception/GovernmentNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/exception/constant/GovernmentErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/mapper/GovernmentMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/mapper/GovernmentMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/presentation/GovernmentController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/presentation/request/CreateGovernmentRequestData.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/presentation/response/GovernmentResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/presentation/web/CreateGovernmentWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/service/GovernmentService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/service/GovernmentServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/mapper/StudentActivityMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/government/service/GovernmentServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/repository/GovernmentRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#486 🔀 :: 485 대학교 리스트 조회 API
  bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/UniversityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/data/response/UniversityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/university/repository/UniversityRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#491 🔀 :: 487 feat/university create and delete api
  bitgouel-api/src/main/kotlin/team/msg/domain/university/exception/AlreadyExistUniversityException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/exception/UniversityHasProfessorConstraintException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/exception/constant/UniversityErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/mapper/UniversityRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/mapper/UniversityRequestRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/UniversityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/data/request/CreateUniversityRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/presentation/data/web/CreateUniversityWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/university/repository/ProfessorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/university/repository/UniversityRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#492 도로명/지번 주소를 좌표로 변환해주는 API를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/common/util/KakaoUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/exception/AddressNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/exception/constant/MapErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/presentation/MapController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/presentation/response/MapResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/service/MapService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/map/service/MapServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/PropertiesScanConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/warmup/WarmUpRunner.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/faq/client/FaqClient.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/KakaoClient.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Address.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Document.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/KakaoAddressResponseData.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Meta.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/RoadAddress.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/config/KakaoFeignConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/interceptor/KakaoRequestInterceptor.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/properties/KakaoProperties.kt
  bitgouel-api/src/main/resources/application.yml
Labels: 1️⃣ Priority: High, ✨ Feature

#497 snake case로 req, res되는 버그
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Address.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Document.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/Meta.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/kakao/client/data/res/RoadAddress.kt
  bitgouel-api/src/main/resources/application.yml
Labels: 1️⃣ Priority: High, 🐞 Bug

#494 유관기관 강사가 존재할 때 유관기관 삭제 못하도록 예외 로직 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/government/exception/GovernmentHasGovernmentInstructorConstraintException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/exception/constant/GovernmentErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/service/GovernmentServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/government/service/GovernmentServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/government/repository/GovernmentInstructorRepository.kt
Labels: 1️⃣ Priority: High

#499 강의 데이터 위치를 추가했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/UpdateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/UpdateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/LectureLocation.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureLocationRepository.kt
Labels: 1️⃣ Priority: High

#504 강사 조회 안되는 버그 수정
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical

#507 학기 해당 없음 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Semester.kt
Labels: 2️⃣ Priority: Medium

#509 🔀 :: 503 test/university domain test code
  bitgouel-api/src/test/kotlin/team/msg/domain/university/service/UniversityServiceImplTest.kt
Labels: ✅ Test

#513 기업 crud API를 개발했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/company/exception/AlreadyExistCompanyException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/exception/CompanyHasCompanyInstructorConstraintException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/exception/constant/CompanyErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/mapper/CompanyRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/mapper/CompanyRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/presentation/CompanyController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/presentation/data/request/CreateCompanyRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/presentation/data/response/CompanyResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/presentation/web/CreateCompanyWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/service/CompanyService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/service/CompanyServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/company/service/CompanyServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/model/Company.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/repository/CompanyInstructorRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/company/repository/CompanyRepository.kt
Labels: 1️⃣ Priority: High

#521 🔀 :: 학교 조회 권한 범위 변경
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: ⚡️ Simple

#522 강의 이수 API 변경사항 적용
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/InvalidStudentGradeException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/exception/constant/StudentErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/CompleteStatus.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/projection/LectureProjection.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentRepository.kt
Labels: 1️⃣ Priority: High

#524 강의 이수 변경사항 테스트코드 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
Labels: 1️⃣ Priority: High

#529 518 update/lecture registration result excel print form
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
Labels: ♻️ Refactor
