Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-02, with the labels that each got.

#247 # 242 Auth Service test 코드 작성
  README.md
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt
Labels: 1️⃣ Priority: High, ✅ Test

#250 🔀 :: 학생 활동 승인 및 거절 API deprecated 처리
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
Labels: 2️⃣ Priority: Medium

#265 🔀 :: 263 유저 수락 API 다수를 수락 가능하도록 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
Labels: 2️⃣ Priority: Medium, ✨ Feature

#267 🔀 :: 266 유저 리스트 api 리팩토링
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/mapper/AdminMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/request/QueryUsersRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/data/web/QueryUsersWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/CustomUserRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#270 🔀 :: 268 학생활동 승인 상태 필드 제거
  bitgouel-api/src/main/kotlin/team/msg/domain/student/handler/StudentActivityEventHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/StudentActivityController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentActivityResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/event/ApproveStudentActivityEvent.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/event/UpdateStudentActivityEvent.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivity.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/StudentActivityHistory.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/StudentActivityHistoryRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/CustomStudentActivityHistoryRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/repository/custom/impl/CustomStudentActivityHistoryRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium

#271 269 강의 개설 권한 변경 및 강의 approveStatus 삭제
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLecturesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium

#273 # 272 자격증 조회 권한을 학생 상세 조회와 같게 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#281 # 264 동아리 서비스 테스트 코드 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/UserController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/certification/service/CertificationServiceImplTest.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple, ✅ Test

#283 # 282 게시글 상세 조회 반환 인자 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/data/response/PostResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#286 # 285 동아리 상세 조회 반환 dto 통합
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/data/response/ClubResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#288 🔀 :: 탈퇴 예정자 response 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple
