Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-04, with the labels that each got.

#361 🔀 :: 360 테이블 변경 구조 롤백 및 락 로직 리팩토링
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/common/annotation/DistributedLock.kt
  bitgouel-api/src/main/kotlin/team/msg/common/aop/lock/DistributedLockAspect.kt
  bitgouel-api/src/main/kotlin/team/msg/common/aop/lock/TransactionAspect.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/PropertiesScanConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/RedisConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/RedissonConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/properties/RedisProperties.kt
  bitgouel-api/src/main/kotlin/team/msg/global/error/GlobalErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/global/exception/LockInterruptedException.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLectureCount.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureCountRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#363 🔀 :: 362 fix/lecture excel print
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#367 fix :: 페이징 옵션 오류
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#373 372 add/user query api retrun parameter
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
Labels: 2️⃣ Priority: Medium

#371 # 370 탈퇴 예정자 리스트 조회 시 인자 추가 반환
  bitgouel-api/src/main/kotlin/team/msg/domain/withdraw/presentation/data/response/WithdrawStudentResponse.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#379 강의 유형과 강의 구분을 enum에서 String 으로 변경했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLinesRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLecturesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLinesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Division.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/LectureType.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor

#381 강의 구분 검색 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllDivisionsRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllDivisionsWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#384 학생이 신청한 강의 내역 조회 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/ForbiddenCompletedLectureException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureDateRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureDateRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureDateRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#389 강의에 신청한, 이수중인 학생 리스트 조회 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/ForbiddenSignedUpLectureException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#388 # 387 JVM 웜업
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/global/warmup/WarmUpRunner.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/client/FaqClient.kt
  bitgouel-api/src/main/kotlin/team/msg/thirdparty/feign/config/FeignConfig.kt
  bitgouel-api/src/main/resources/application.yml
  bitgouel-domain/src/main/kotlin/team/msg/domain/student/model/Student.kt
Labels: ⚡️performance

#390 강의 이수 여부 수정 api 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#392 강의 데이터에 essentialComplete 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
Labels: 1️⃣ Priority: High

#394 강의 개설 권한 확대
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High
