Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-05, with the labels that each got.

#398 유저가 학생일 때 자신이 신청한 강의 리스트를 볼 수 있도록 권한을 변경했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#400 비밀번호를 변경한 후 인증을 초기화하도록 로직을 추가했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple

#401 🔀 :: 강의 수강 신청 결과 엑셀 다운로드
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
Labels: ♻️ Refactor, ✨ Feature

#407 🔀 :: CD Build 시에 redis 추가
  .github/workflows/bitgouel-cd.yml
Labels: 🌏 Deploy

#437 handler 처리 반대로 된거 수정
  bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAccessDeniedHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAuthenticationEntryPointHandle.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#435 비밀번호 변경 예외 코드 401 -> 400
  bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/MisMatchPasswordException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/exception/constant/UserErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
Labels: 2️⃣ Priority: Medium

#433 강의 서비스 코드를 리팩토링했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/projection/LectureProjection.kt
Labels: 3️⃣ Priority: Low
