Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-08, with the labels that each got.

#531 학교 상세 조회 API를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/school/presentation/SchoolController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#537 학교 수정 시 학교 이름이 변경되지 않으면 학교 수정이 되지않는 버그를 고쳤습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/school/repository/SchoolRepository.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#541 동아리 수정 시 나타나던 버그 수정
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/club/repository/ClubRepository.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#543 update :: query lecture date desc -> asc
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureDateRepositoryImpl.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#545 강의 신청 시작일과 마감일이 변경되지 않는 오류를 고쳤습니다
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
Labels: 🐞 Bug

#555 🔀 :: 인덱스 자동증가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
Labels: 0️⃣ Priority: Critical

#559 강의 이수 완료 취소 API 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#562 강의 신청 학생 이수 여부에 따라 필터링하여 조회
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllSignedUpStudentsRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllSignedUpStudentsWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomRegisteredLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomRegisteredLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High

#564 🔀 :: 대용량 데이터 조회 및 처리 개선
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
Labels: ♻️ Refactor

#569 🔀 :: 공유 캐시 작업
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/domain/club/presentation/ClubController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/club/service/ClubServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/company/service/CompanyServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/government/service/GovernmentServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/school/service/SchoolServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/university/service/UniversityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/CacheConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/properties/CacheProperties.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
Labels: 3️⃣ Priority: Low
