Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-03, with the labels that each got.

#290 🔀 :: 289 어드민 도메인 테스트 코드 작성
  bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt
Labels: ✅ Test

#280 강사 검색 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/CustomUserRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/custom/impl/CustomUserRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#292 🔀 :: student entity 삭제 시 withdraw student entity 함께 삭제
  bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/withdraw/repository/WithdrawStudentRepository.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#294 게시글 url 검토 방식 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/post/mapper/PostRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/CreatePostWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/UpdatePostWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/validation/URLList.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/presentation/web/validation/URLListValidator.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#298 🔀 :: 297 유저 거절 api 다수 거절 가능하도록 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/presentation/AdminController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/admin/service/AdminServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/admin/service/AdminServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/user/repository/UserRepository.kt
Labels: ✨ Feature

#284 강의 테스트코드를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
Labels: 1️⃣ Priority: High, ✅ Test

#304 구분, 계열 등 강의 변경사항을 적용했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllDepartmentsRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/QueryAllLinesRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllDepartmentsWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/QueryAllLinesWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Division.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Semester.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/CustomLectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple, ✨ Feature

#306 🔀 :: 303 학생활동 학생 단위로 조회 API 권한 범위 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/student/service/StudentActivityServiceImplTest.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#309 마이페이지와 동아리 학생 리스트에 user id 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/student/presentation/data/response/StudentResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/club/service/ClubServiceImplTest.kt
Labels: 0️⃣ Priority: Critical

#307 강의 수강 날짜 단일 -> 리스트 적용
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/CreateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/LectureDateRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/LectureDateWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/LectureDate.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureDateRepository.kt
Labels: 1️⃣ Priority: High, ♻️ Refactor, ⚡️ Simple

#313 🔀 :: 어드민 학생활동 학생 단위로 조회 접근 허용
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#315 이미 답변이 존재하는 문의사항에 예외
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/AlreadyAnsweredInquiryException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/exception/constant/InquiryErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/inquiry/service/InquiryServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/inquiry/repository/InquiryAnswerRepository.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#318 이메일 도메인 세팅
  bitgouel-domain/src/main/kotlin/team/msg/domain/email/model/EmailAuthentication.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/email/repository/EmailAuthenticationRepository.kt
Labels: 1️⃣ Priority: High, ⚙ Setting

#321 인증링크 이메일 전송 api 작성
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/BitgouelApplication.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/exception/AlreadyAuthenticatedEmailException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/exception/EmailSendFailException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/exception/TooManyEmailAuthenticationRequestException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/exception/constant/EmailErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/mapper/EmailRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/mapper/EmailRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/presentation/EmailController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/presentation/data/request/SendAuthenticationEmailRequestData.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/presentation/web/SendAuthenticationEmailWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/service/EmailService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/eamil/service/EmailServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/PropertiesScanConfig.kt
  bitgouel-api/src/main/kotlin/team/msg/global/config/properties/EmailProperties.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/main/resources/application.yml
  bitgouel-api/src/main/resources/templates/authentication-email-template.html
  bitgouel-domain/src/main/kotlin/team/msg/domain/email/model/EmailAuthentication.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#320 🔀 :: 316 강의 수강 신청 결과 엑셀 출력 API
  bitgouel-api/build.gradle.kts
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Division.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/enums/Semester.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
Labels: ✨ Feature

#330 이메일 인증 링크 클릭 시 blank 페이지가 띄워지던 오류
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/EmailController.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#328 이메일 인증 여부를 검증하는 api를 작성했습니다.
  bitgouel-api/src/main/kotlin/team/msg/domain/email/mapper/EmailRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/mapper/EmailRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/EmailController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/data/request/CheckEmailAuthenticationRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/data/request/SendAuthenticationEmailRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/data/response/CheckEmailAuthenticationResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/web/CheckAuthenticationEmailWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#334 # 332 Script time out 늘리기
  appspec.yml
  bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAccessDeniedHandler.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/handler/CustomAuthenticationEntryPointHandle.kt
Labels: 0️⃣ Priority: Critical

#336 이메일 인증여부 조회 api request 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/email/mapper/EmailRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/mapper/EmailRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/EmailController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/data/request/CheckEmailAuthenticationRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/presentation/web/CheckAuthenticationEmailWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#346 이메일 인증 전송 메일 템플릿 변경
  bitgouel-api/src/main/resources/templates/authentication-email-template.html
Labels: 1️⃣ Priority: High

#351 이메일 새로 전송 시 코드 새로 발급
  bitgouel-api/src/main/kotlin/team/msg/domain/email/service/EmailServiceImpl.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#353 🔀 :: 327 강의 수강신청 동시성 문제 해결
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
Labels: ♻️ Refactor, 🐞 Bug

#355 🔀 :: 354 수강신청 API 동시성 제어 리팩토링
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/RegisteredLectureCountNotFoundException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/exception/constant/LectureErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/RegisteredLectureServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/RegisteredLectureCount.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureCountRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/RegisteredLectureRepository.kt
Labels: ♻️ Refactor

#359 전화번호 반환 형식 변경
  bitgouel-api/src/main/kotlin/team/msg/domain/user/presentation/data/response/UserResponse.kt
Labels: 2️⃣ Priority: Medium, ♻️ Refactor
