Repository School-of-Company/Bitgouel-Server, pull requests merged in 2024-06, with the labels that each got.

#442 readme를 수정했습니다.
  README.md
  assets/img/bitgouel_erd.png
Labels: 1️⃣ Priority: High, 📝 Docs

#446 비밀번호 변경 시 기존 비밀번호와 변경할 비밀번호가 같으면 예외를 발생
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/exception/SameAsOldPasswordException.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/exception/constant/AuthErrorCode.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/service/UserServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt
Labels: 1️⃣ Priority: High

#447 🔀 :: 445 repository의 save 메서드 호출 시 성능 개선
  README.md
  bitgouel-api/src/main/kotlin/team/msg/common/util/StudentUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/common/util/UserUtil.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/auth/service/AuthServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/certification/service/CertificationServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/inquiry/service/InquiryServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/post/service/PostServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/student/service/StudentActivityServiceImpl.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/auth/service/AuthServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/common/entity/BaseUUIDEntity.kt
Labels: 🐞 Bug

#451 유저 도메인 테스트코드를 작성했습니다.
  bitgouel-api/src/test/kotlin/team/msg/domain/user/service/UserServiceImplTest.kt
Labels: 2️⃣ Priority: Medium

#461 🔀 :: 460 hikaricp datasource autocommit option false로 설정
  bitgouel-api/src/main/resources/application-local.yml
Labels: ⚡️performance

#463 🔀 :: rollback datasource.url
  bitgouel-api/src/main/resources/application-local.yml
Labels: 🐞 Bug

#465 max registered user 제한 삭제
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/CreateLectureWebRequest.kt
Labels: 2️⃣ Priority: Medium, ⚡️ Simple

#472 강의 정보 수정 api 작성
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapper.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/mapper/LectureRequestMapperImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/LectureController.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/request/UpdateLectureRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/web/UpdateLectureWebRequest.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureService.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/service/LectureServiceImpl.kt
  bitgouel-api/src/main/kotlin/team/msg/global/security/SecurityConfig.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureDateRepository.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#475 강의 상세조회에 user id 값 추가
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/test/kotlin/team/msg/domain/lecture/service/LectureServiceImplTest.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#459 🔀 :: 456 강의 데이터 논리적 삭제 구현
  bitgouel-api/src/main/kotlin/team/msg/domain/lecture/presentation/data/response/LectureResponse.kt
  bitgouel-api/src/main/kotlin/team/msg/domain/user/handler/UserEventHandler.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/model/Lecture.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/LectureRepository.kt
  bitgouel-domain/src/main/kotlin/team/msg/domain/lecture/repository/custom/impl/CustomLectureRepositoryImpl.kt
Labels: 1️⃣ Priority: High, ✨ Feature
